Repository tailwindlabs/tailwindcss, pull requests merged in 2024-10, with the labels that each got.

#14448 Add support for `important` in v4
  CHANGELOG.md
  packages/tailwindcss/src/compat/apply-compat-hooks.ts
  packages/tailwindcss/src/compat/config.test.ts
  packages/tailwindcss/src/compat/config/resolve-config.ts
  packages/tailwindcss/src/compat/config/types.ts
  packages/tailwindcss/src/compile.ts
  packages/tailwindcss/src/design-system.ts
  packages/tailwindcss/src/important.test.ts
  packages/tailwindcss/src/index.ts
  packages/tailwindcss/src/intellisense.test.ts
Labels: v4

#14625 Don't set `display: none` on elements that use `hidden="until-found"`
  CHANGELOG.md
  src/css/preflight.css
Labels: v3

#14631 Don't set `display: none` on elements that use `hidden="until-found"`
  CHANGELOG.md
  packages/@tailwindcss-postcss/src/__snapshots__/index.test.ts.snap
  packages/tailwindcss/preflight.css
Labels: v4

#14716 Vite: Fix issues when loading files via static asset queries
  CHANGELOG.md
  integrations/vite/index.test.ts
  packages/@tailwindcss-vite/src/index.ts
  playgrounds/vite/package.json
  playgrounds/vite/src/animate.js
  playgrounds/vite/src/app.tsx
  playgrounds/vite/src/bar.tsx
  playgrounds/vite/src/foo.tsx
  playgrounds/vite/src/forms.js
  playgrounds/vite/src/index.css
  playgrounds/vite/src/index.html
  playgrounds/vite/src/main.tsx
  playgrounds/vite/src/plugin.js
  playgrounds/vite/src/typography.js
  pnpm-lock.yaml
Labels: merge-queue

#14748 Add codemod for migrating `@variants` and `@responsive` directives
  CHANGELOG.md
  integrations/upgrade/index.test.ts
  packages/@tailwindcss-upgrade/src/codemods/migrate-tailwind-directives.test.ts
  packages/@tailwindcss-upgrade/src/codemods/migrate-tailwind-directives.ts
  packages/@tailwindcss-upgrade/src/codemods/migrate-variants-directive.test.ts
  packages/@tailwindcss-upgrade/src/codemods/migrate-variants-directive.ts
  packages/@tailwindcss-upgrade/src/migrate.ts
Labels: merge-queue

#14749 Add codemod for migrating the `@screen` directive
  CHANGELOG.md
  packages/@tailwindcss-upgrade/src/codemods/migrate-media-screen.test.ts
  packages/@tailwindcss-upgrade/src/codemods/migrate-media-screen.ts
Labels: merge-queue

#14737 Upgrade: Reduce number of false-positive migrations of the important modifier
  CHANGELOG.md
  integrations/upgrade/js-config.test.ts
  packages/@tailwindcss-upgrade/src/template/codemods/important.test.ts
  packages/@tailwindcss-upgrade/src/template/codemods/important.ts
  packages/@tailwindcss-upgrade/src/template/migrate.ts
Labels: merge-queue

#14747 Always emit keyframes registered in `addUtilities`
  CHANGELOG.md
  integrations/cli/plugins.test.ts
  packages/tailwindcss/src/compat/plugin-api.test.ts
  packages/tailwindcss/src/compat/plugin-api.ts
Labels: merge-queue

#14754 Upgrade: Migrate `max-w-screen-*` candidates
  CHANGELOG.md
  integrations/upgrade/index.test.ts
  packages/@tailwindcss-upgrade/src/template/codemods/max-width-screen.test.ts
  packages/@tailwindcss-upgrade/src/template/codemods/max-width-screen.ts
  packages/@tailwindcss-upgrade/src/template/codemods/theme-to-var.test.ts
  packages/@tailwindcss-upgrade/src/template/migrate.ts
Labels: merge-queue

#14739 Escape JS theme configuration keys
  CHANGELOG.md
  packages/tailwindcss/src/compat/apply-config-to-theme.test.ts
  packages/tailwindcss/src/compat/apply-config-to-theme.ts
  packages/tailwindcss/src/compat/plugin-api.test.ts
  packages/tailwindcss/src/compat/plugin-api.ts
  packages/tailwindcss/src/compat/plugin-functions.ts
  packages/tailwindcss/src/utils/escape.test.ts
  packages/tailwindcss/src/utils/escape.ts
Labels: merge-queue

#14736 Upgrade: Migrate JS theme configuration keys with dot and slash in the property name
  CHANGELOG.md
  integrations/upgrade/js-config.test.ts
  packages/@tailwindcss-upgrade/src/migrate-js-config.ts
  packages/tailwindcss/src/compat/apply-config-to-theme.test.ts
Labels: merge-queue

#14799 Make `config()` path arg optional in v4 plugin API
  CHANGELOG.md
  packages/tailwindcss/src/compat/config/resolve-config.ts
  packages/tailwindcss/src/compat/config/types.ts
  packages/tailwindcss/src/compat/plugin-api.test.ts
  packages/tailwindcss/src/compat/plugin-api.ts
Labels: v4

#14829 Fix new file detection in PostCSS plugin
  CHANGELOG.md
  crates/oxide/src/lib.rs
  crates/oxide/src/scanner/allowed_paths.rs
  crates/oxide/src/scanner/detect_sources.rs
  crates/oxide/tests/scanner.rs
  integrations/postcss/index.test.ts
  integrations/utils.ts
Labels: v4
